source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!


target "Example" do
    pod "URBNValidator", :path => "../"

    target "URBNValidator_Tests" do
        inherit! :search_paths
    end
end